"""Criação da tabela Tarefa

Revision ID: 3ce95943400c
Revises: 
Create Date: 2026-06-28 19:39:27.349164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce95943400c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pendente', 'Em andamento', 'Concluída', name='StatusTarefa'), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_de_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_de_exclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
